export { Home } from "./Home"
export { LogIn } from "./LogIn"
export { SignUp } from "./SignUp"
export { Admin } from "./Admin"
export { Avocats  } from "./Avocats"
export { DetailsAvocats } from "./DetailsAvocat"
export { SignUpDetails } from "./SignUpDetails"